name:

on: push

jobs:
  markdown-to-pdf:
    runs-on: ubuntu-18.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Setup"
        run: mkdir build/
      - name: "YAML, LaTeX -> [pandoc] -> LaTeX"
        uses: docker://pandoc/core:latest
        with:
          args: >-
            --from=markdown
            --template=src/templates/cv.tex
            --metadata-file=src/cv.yaml
            /dev/null
            -o build/cv.tex
      - name: "LaTeX -> [latexmk] -> PDF"
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: env BIBINPUTS=src/bib latexmk -lualatex -pdf build/cv.tex -output-directory=build
      - name: "Rename"
        run: mv build/cv.pdf build/schuyler-eldridge-cv.pdf
      - name: "Upload build directory"
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
          retention-days: 1
      - name: "Create Release if Tagged"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: build/schuyler-eldridge-cv.pdf
